---
# tasks file for roles/iosplay
#
#
- hosts: csr01p
  tasks:
    - name: execute a ios command via proxy
      ios_command:
        commands:
          - 'show running config'
      register: result

    - debug:
          msg: "{{ result }}"
