---
# tasks file for roles/iosplay
#
#
- hosts: iosxr02
  tasks:
    - name: Delete interface aggregate (setup)
      iosxr_interface:
        aggregate:
        - name: GigabitEthernet0/0/0/3
        - name: GigabitEthernet0/0/0/2
        state: absent
    
    - name: Add interface aggregate
      iosxr_interface:
        aggregate:
        - { name: GigabitEthernet0/0/0/3, mtu: 256, description: test-interface-1 }
        - { name: GigabitEthernet0/0/0/2, mtu: 516, description: test-interface-2 }
        speed: 100
        duplex: full
        state: present
      register: result
    
    - assert:
        that:
          - 'result.changed == true'
          - '"interface GigabitEthernet0/0/0/3 speed 100" in result.commands'
          - '"interface GigabitEthernet0/0/0/3 description test-interface-1" in result.commands'
          - '"interface GigabitEthernet0/0/0/3 duplex full" in result.commands'
          - '"interface GigabitEthernet0/0/0/3 mtu 256" in result.commands'
          - '"interface GigabitEthernet0/0/0/2 speed 100" in result.commands'
          - '"interface GigabitEthernet0/0/0/2 description test-interface-2" in result.commands'
          - '"interface GigabitEthernet0/0/0/2 duplex full" in result.commands'
          - '"interface GigabitEthernet0/0/0/2 mtu 516" in result.commands'

