---
- hosts: rtr1
  tasks:
    - name: Enable netconf on iosxr                                                     
      iosxr_netconf:                                                                                                         
        netconf_port: 830                                                                                         
        netconf_vrf:  'default'                                                                                         
        state: present                                                                                                       
      register: result                                                                                                       
                                                                                                                             
    - assert: &true                                                                                                                
        that:                                                                                                                
          - 'result.changed == true'                                                                                         
