---
- hosts: rtr1
  tasks:
    - name: Enable bgp iosxr                                                     
      json_parser:                                                                                                         
          src: bgp_edit_config.json
          output: bgp_edit_config_exp.xml
      register: result                                                                                                       
                                                                                                                             
    - assert: &true                                                                                                                
        that:                                                                                                                
          - 'result.changed == true'                                                                                         
