# tasks file for roles/iosplay
#
#
- hosts: asa01
  tasks:
    - name: config acl
      asa_acl:
        lines:
          - access-list ACL-ANSIBLE extended permit tcp any any eq 82
          - access-list ACL-ANSIBLE extended permit tcp any any eq www
          - access-list ACL-ANSIBLE extended permit tcp any any eq 97
          - access-list ACL-ANSIBLE extended permit tcp any any eq 98
        match: strict
        replace: block 
      register: result
      
    - name: change the acl
      asa_acl:
        lines:
          - access-list ACL-ANSIBLE extended permit tcp any any eq 82
          - access-list ACL-ANSIBLE extended permit tcp any any eq www
          - access-list ACL-ANSIBLE extended permit tcp any any eq 97
          - access-list ACL-ANSIBLE extended permit tcp any any eq 98
          - access-list ACL-ANSIBLE extended permit tcp any any eq 99
        match: strict
        replace: block 
      register: result
