---
- hosts: rtr1
  tasks:
    - name: Confgure interface parameters using platform agnostic module                                                     
      net_interface:                                                                                                         
        name: GigabitEthernet0/0/0/2                                                                                         
        description: test-interface                                                                                          
        speed: 100                                                                                                           
        duplex: half                                                                                                         
        mtu: 512                                                                                                             
        state: present                                                                                                       
      register: result                                                                                                       
                                                                                                                             
    - assert:                                                                                                                
        that:                                                                                                                
          - 'result.changed == true'                                                                                         
          - '"interface GigabitEthernet0/0/0/2 description test-interface" in result.commands'                               
          - '"interface GigabitEthernet0/0/0/2 speed 100" in result.commands'                                                
          - '"interface GigabitEthernet0/0/0/2 duplex half" in result.commands'                                              
          - '"interface GigabitEthernet0/0/0/2 mtu 512" in result.commands'        
