---
# tasks file for roles/iosplay
#
#
- hosts: iosl202
  tasks:
    -  name: collect facts
       ios_facts:
          gather_subset:
              - all
       register: result
      
    - debug:
          msg: "{{ result }}"

