---
# tasks file for roles/iosplay
#
#
- hosts: iosxr01
  tasks:
    - name: copy file from controller to iosxr
      network_put:
          src: biox.cfg
          dest: '/misc/scratch/biox11.cfg'
      register: result
      
    - debug:
          msg: "{{ result }}"

- hosts: nxos01
  tasks:
    - name: copy file from controller to nxos + scp (Default)
      network_put:
          src: nxos_ansible.cfg  
      register: result
      tags: basic

    - debug:
          msg: "{{ result }}"

    - name: copy file from controller to nxos + dest specified
      network_put:
          src: nxos_ansible.cfg 
          dest: 'bootflash:nxos_24_04_2018.cfg'
      register: result
      tags: dest
      
    - debug:
          msg: "{{ result }}"

    - name: copy file from controller to nxos + sftp protocol
      network_put:
          src: nxos_ansible.cfg 
          protocol: sftp 
      register: result
      tags: sftp
      
    - debug:
          msg: "{{ result }}"

    - name: copy large config file
      network_put:
          src: 2mb_config.cfg
      register: result
      tags: large
      
    - debug:
          msg: "{{ result }}"

- hosts: ios02
  tasks:
    - name: copy file from controller to ios + scp (Default)
      network_put:
          src: aios.cfg  
      register: result
      tags: basic

    - debug:
          msg: "{{ result }}"

  tasks:
    - name: copy file from ios to ansible ctrl
      network_get:
          src: 'ios.cfg'
      register: result
      tags: basic_get

    - debug:
          msg: "{{ result }}"

- hosts: iosxr02
  tasks:
    - name: copy file from controller to iosxr02 + scp (Default)
      network_put:
          src: iosxr.cfg
          dest: 'disk0:/aios1.cfg'
      register: result
      tags: basic

    - debug:
          msg: "{{ result }}"

  tasks:
    - name: copy file from iosxr to ansible ctrl
      network_get:
          src: '/misc/scratch/a.cfg'
      register: result
      tags: basic_get

    - debug:
          msg: "{{ result }}"
